### PR TITLE
Upgrade appboy

### PR DESCRIPTION
**Pull request by trevorrjohn**

### CODE REVIEW

**Comment by blimmer** [comment]
1.6.3 should be covered today with the semver range, but bumping it to ensure the dependency is correct is totally fine. I'll merge this and release once tests pass.

Thanks!!

**Comment by trevorrjohn** [comment]
yeah, I figured that it was best to just bump it for clarity sake.

**Comment by blimmer** [comment]
also FYI i'm going to checkout your branch and remove the "bump version" commit - i like to have the bump version and changelog generated on master in the same commit so it's easy for addon consumers to view what changed.

**Comment by blimmer** [comment]
published - thanks again.

**Pull request closed without merging**
